import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: '开始使用',
  //     items: [
  //       'product-introduction', // 确保这是文档的正确路径
  //       'quick-start', // 其他相关文档
  //     ],
  //     collapsed: false, // 确保默认展开
  //   },
  //   {
  //     type: 'category',
  //     label: '平台能力',
  //     items: [
  //       'capabilities', // 确保这是文档的正确路径
  //     ],
  //     collapsed: false, // 确保默认展开
  //   },
  //   {
  //     type: 'category',
  //     label: 'API手册',
  //     items: [
  //       'api-manual', // 确保这是文档的正确路径
  //     ],
  //     collapsed: false, // 确保默认展开
  //   },
  //   {
  //     type: 'category',
  //     label: '场景示例',
  //     items: [
  //       'user-cases', // 确保这是文档的正确路径
  //     ],
  //     collapsed: false, // 确保默认展开
  //   },
  // ],
    { type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
